### ISSUE TITLE
Consider adding an open-source license

### ISSUE THREAD

**Issue by Veetaha** [CAD97/sorbus#44]

**Comment by CAD97** [comment]
(whoops, I just haven't gotten around to actually adding the license now that the experiment actually works; thanks for the reminder. Informally, consider the code available under `MIT OR APACHE-2.0` (same as Rowan). I'll get the formal licenses added when I get a chance – probably tomorrow.)

**Comment by CAD97** [comment]
(sorry this took so long!)
